# Generated by Django 4.1.3 on 2024-01-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(default='ratchanon', max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.CharField(choices=[('standard', 'ธรรมดา'), ('superior', 'ซูพรีม'), ('deluxe', 'ดีลักซ์')], max_length=10),
        ),
    ]
