# Generated by Django 4.1.3 on 2024-01-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_alter_reservation_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('1', 'ธรรมดา'), ('2', 'ซูพีเรียร์'), ('3', 'ดีลักซ์')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='status',
            field=models.CharField(choices=[('1', 'ว่าง'), ('2', 'ไม่ว่าง')], max_length=15),
        ),
    ]
